### ISSUE TITLE
Receiver should be able to tell if crawler finished processing.

### ISSUE THREAD

**Issue by stolowski** [pilebones/go-udev#7]
Hi, I think it would be very useful for the client of crawler.ExistingDevices to know if there are more devices, or if the walk over existing devices was completed. I've proposed the PR https://github.com/pilebones/go-udev/pull/6/files that adds this capability.

**Comment by pilebones** [comment]
Indeed, very useful, this feature miss in the crawler. Thank to your suggestion.
